config/routes.rb
Rails.application.routes.draw do
  resources :people
  devise_for :users
  resources :products
  resources :weddings
  resources :projects
  resources :dysphoria
  resources :misens
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root to: 'homes#index'

  get 'people', to: 'page#people'
  get 'weddings', to: 'page#weddings'
  get 'projects', to: 'page#projects'
  get 'dysphoria', to: 'page#dysphoria'
  get 'contact', to: 'page#contact'
  get 'mise_en_conformite', to: 'page#mise_en_conformite'
  get 'administration', to: 'page#administration'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dysphorium.rb
class Dysphorium < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/home.rb
class Home < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/misen.rb
class Misen < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/page.rb
class Page < ApplicationRecord

end

app/models/person.rb
class Person < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,  :registerable
  devise :database_authenticatable,
          :rememberable, :trackable, :validatable
end

app/models/wedding.rb
class Wedding < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def home_params
      params.require(:home).permit(:name, :description, :photo, :photo_cache)
    end
  end

app/controllers/misens_controller.rb
class MisensController < ApplicationController
  before_action :set_misen, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!
  # GET /misens
  # GET /misens.json
  def index
    @misens = Misen.all
  end

  # GET /misens/1
  # GET /misens/1.json
  def show
  end

  # GET /misens/new
  def new
    @misen = Misen.new
  end

  # GET /misens/1/edit
  def edit
  end

  # POST /misens
  # POST /misens.json
  def create
    @misen = Misen.new(misen_params)

    respond_to do |format|
      if @misen.save
        format.html { redirect_to @misen, notice: 'Misen was successfully created.' }
        format.json { render :show, status: :created, location: @misen }
      else
        format.html { render :new }
        format.json { render json: @misen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /misens/1
  # PATCH/PUT /misens/1.json
  def update
    respond_to do |format|
      if @misen.update(misen_params)
        format.html { redirect_to @misen, notice: 'Misen was successfully updated.' }
        format.json { render :show, status: :ok, location: @misen }
      else
        format.html { render :edit }
        format.json { render json: @misen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /misens/1
  # DELETE /misens/1.json
  def destroy
    @misen.destroy
    respond_to do |format|
      format.html { redirect_to misens_url, notice: 'Misen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_misen
      @misen = Misen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def misen_params
      params.require(:misen).permit(:name, :description, :photo, :photo_cache)
    end
  end

app/controllers/page_controller.rb
class PageController < ApplicationController
  skip_before_action :authenticate_user!, only: [:architecture, :people, :weddings, :mise_en_conformite, :projects, :contact, :homepage, :dysphoria ]

  def homepage
  end

  def architecture
  end

  def people
  end

  def weddings
  end

  def projects
  end

  def dysphoria
  end

  def mise_en_conformite
  end

  def contact
  end

  def administration

  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/homes/_form.html.erb
<%= simple_form_for(@home) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Homepage</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title>Airbnb home</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/style.css">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
   <div class="navbar-wagon1">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logoben.jpg", alt: "Logo", width: 64, height: 64 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>


      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if !current_user.nil? %>

          <% else %>
          <%= image_tag "http://www.pi-cube.com/wp-content/uploads/2015/04/team-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>

      <!-- Login link (when logged out) -->

      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/pages/prices">Prices</a></li>
          <li><a href="/pages/converter">Converter</a></li>
          <li><a href="/pages/tutorial">Buy bitcoin</a></li>
          <li><a href="/pages/wallet">Wallet</a></li>
          <li>              <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container12" >

      <div class="1">
        <br>
        <nav>
          <section id="content" class="content13">
            <div class="navbar_wrap">
              COLLECTIONS
              <ul class="boxx">
                <li><a href="products">Architecture</a></li>
                <li><a href="people">People</a></li>
                <li><a href="weddings">Weddings</a></li>
                <li><a href="projects">Projects</a></li>
                <li><a href="dysphoria">Dysphoria</a></li>
                <li><a href="misens">Mise en </br> conformité</a></li>
                <li><a href="contact">Contact</a></li>
              </ul>
            </div>
          </section>
        </nav>
      </div>

      <div class= "content1 "   style="float: left;padding: 5px 15px;">
      </div>


      <div class="2">
        <div class="masonry">



          <% @homes.each do |home| %>

          <div class="item">

            <tr>
             <td><%= cl_image_tag home.photo %></td>
             <% if !current_user.nil? and current_user.admin?  %>
             <br>
             <td><%= link_to 'Show', home %></td>
             <td><%= link_to 'Edit', edit_home_path(home) %></td>
             <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
             <% end %>
           </tr>
         </div>
         <% end %>
         <br>
         <% if !current_user.nil? and current_user.admin? %>
         <%= link_to 'New Photo homes', new_home_path %>
         <% end %>

       </div>
     </div>

     <p id="notice"><%= notice %></p>

     <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <ul class="list-inline">
              <li><a href="https://www.instagram.com/benbaltus/"><i class="fa fa-instagram"></i></a></li>
              <li><a href="https://www.facebook.com/benjamingary.baltus/photos_all"><i class="fa fa-facebook"></i></a></li>
            </ul>
          </div>
          <div class="col-xs-8 text-right">
            <p>Website by Jules Wittock<a class="point" href="administration">.</a></p>
          </div>
        </div>
      </div>
    </div>




    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
  <script type="text/javascript">


    $(window).scroll(function() {
      var scroll = $(window).scrollTop();
      var x = $(window).height();

     //>=, not <=
     if (scroll >= x) {
      $(".navbar-wagon").addClass("navfixe");
      $(".navbar-wagon").removeClass("navhide");
      $("#content").addClass("navfixe1");
      $(".content1").addClass("navfixe2");

    }

    if (scroll < x) {
      $(".navbar-wagon").removeClass("navfixe");
      $(".navbar-wagon").addClass("navhide");
      $("#content").removeClass("navfixe1");
      $(".content1").removeClass("navfixe2");

    }
  });



</script>
</html>

app/views/homes/new.html.erb
<h1>New Homepage</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @home.description %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>


<%= cl_image_tag @home.photo, height: 300, width: 400, crop: :fill %>

app/views/misens/_form.html.erb
<%= simple_form_for(@misen) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/misens/edit.html.erb
<h1>Editing Mise en Conformité</h1>

<%= render 'form', misen: @misen %>

<%= link_to 'Show', @misen %> |
<%= link_to 'Back', misens_path %>

app/views/misens/index.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title>Airbnb home</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/style.css">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
   <div class="navbar-wagon1">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logoben.jpg", alt: "Logo", width: 64, height: 64 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>


      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if !current_user.nil? %>

          <% else %>
          <%= image_tag "http://www.pi-cube.com/wp-content/uploads/2015/04/team-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>

      <!-- Login link (when logged out) -->

      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/pages/prices">Prices</a></li>
          <li><a href="/pages/converter">Converter</a></li>
          <li><a href="/pages/tutorial">Buy bitcoin</a></li>
          <li><a href="/pages/wallet">Wallet</a></li>
          <li>              <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container12" >

      <div class="1">
        <br>
        <nav>
          <section id="content" class="content13">
            <div class="navbar_wrap">
              COLLECTIONS
              <ul class="boxx">
                <li><a href="products">Architecture</a></li>
                <li><a href="people">People</a></li>
                <li><a href="weddings">Weddings</a></li>
                <li><a href="projects">Projects</a></li>
                <li><a href="dysphoria">Dysphoria</a></li>
                <li><a href="misens">Mise en </br> conformité</a></li>
                <li><a href="contact">Contact</a></li>
              </ul>
            </div>
          </section>
        </nav>
      </div>

      <div class= "content1 "   style="float: left;padding: 5px 15px;">
      </div>


      <div class="2">
        <div class="masonry">



          <% @misens.each do |misen| %>

          <div class="item">

            <tr>
              <td>
                <%= cl_image_tag misen.photo %>
              </td>
              <% if !current_user.nil? and current_user.admin?  %>
              <br>
              <td>
                <%= link_to 'Show', misen %>
              </td>
              <td>
                <%= link_to 'Edit', edit_misen_path(misen) %>
              </td>
              <td>
                <%= link_to 'Destroy', misen, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
              <% end %>
            </tr>
          </div>
          <% end %>
          <br>
          <% if !current_user.nil? and current_user.admin? %>
          <%= link_to 'New Photo mise en conformité', new_misen_path %>
          <% end %>

        </div>
      </div>

      <p id="notice"><%= notice %></p>

      <div id="footer">
        <div class="container">
          <div class="row">
            <div class="col-xs-4">
              <ul class="list-inline">
                <li><a href="https://www.instagram.com/benbaltus/"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.facebook.com/benjamingary.baltus/photos_all"><i class="fa fa-facebook"></i></a></li>
              </ul>
            </div>
            <div class="col-xs-8 text-right">
              <p>Website by Jules Wittock<a class="point" href="administration">.</a></p>
            </div>
          </div>
        </div>
      </div>




      <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
    <script type="text/javascript">


      $(window).scroll(function() {
        var scroll = $(window).scrollTop();
        var x = $(window).height();

     //>=, not <=
     if (scroll >= x) {
      $(".navbar-wagon").addClass("navfixe");
      $(".navbar-wagon").removeClass("navhide");
      $("#content").addClass("navfixe1");
      $(".content1").addClass("navfixe2");

    }

    if (scroll < x) {
      $(".navbar-wagon").removeClass("navfixe");
      $(".navbar-wagon").addClass("navhide");
      $("#content").removeClass("navfixe1");
      $(".content1").removeClass("navfixe2");

    }
  });



</script>
</html>

app/views/misens/new.html.erb
<h1>New Mise en conformité</h1>

<%= render 'form', misen: @misen %>

<%= link_to 'Back', misens_path %>

app/views/misens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @misen.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @misen.description %>
</p>

<%= link_to 'Edit', edit_misen_path(@misen) %> |
<%= link_to 'Back', misens_path %>


<%= cl_image_tag @misen.photo, height: 300, width: 400, crop: :fill %>